theme = "gruvbox"

[editor]
auto-format             = false
auto-pairs              = false
bufferline              = "multiple"
end-of-line-diagnostics = "hint"
line-number             = "relative"
mouse                   = false
popup-border            = "all"
shell                   = ["/bin/fish", "-c"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.inline-diagnostics]
cursor-line = "error"

[editor.lsp]
display-progress-messages = true

[editor.soft-wrap]
enable = true

[editor.statusline]
left = [
  "mode",
  "spinner"
]
center = [
  "file-name",
  "read-only-indicator"
]
right = [
  "diagnostics",
  "selections",
  "register",
  "position",
  "position-percentage",
  "file-encoding"
]
