theme = "gruvbox"

[editor]
mouse        = false
shell        = ["/bin/fish", "-c"]
line-number  = "relative"
auto-format  = false
bufferline   = "always"
popup-border = "all"

[editor.statusline]
left   = ["mode", "spinner"]
center = ["version-control", "file-type", "read-only-indicator"]
right  = ["diagnostics", "selections", "register", "position", "position-percentage", "file-encoding"]

[editor.lsp]
display-inlay-hints = false

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false

# Disable auto-pairs by configuring this empty table instead of the boolean in
# the `editor` section. It's a TOML style preference for me.
[editor.auto-pairs]

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true
