[user]
name  = "Matthew Sanabria"
email = "me@matthewsanabria.dev"

[[--scope]]
--when.repositories = ["~/oxide"]
[--scope.user]
email = "matthew.sanabria@oxide.computer"

[templates]
git_push_bookmark = '"sudomateo/" ++ change_id.short()'
