[user]
name  = "Matthew Sanabria"
email = "me@matthewsanabria.dev"

[[--scope]]
--when.repositories = ["~/src/oxide"]
[--scope.user]
email = "matthew.sanabria@oxide.computer"

[ui]
default-command = ["log"]

[git]
colocate = true
push-new-bookmarks = true

[templates]
# Customize the bookmark name when running `jj git push --change`.
git_push_bookmark = "'sudomateo/' ++ change_id.short()"

[template-aliases]
# Use relative timestamps.
"format_timestamp(timestamp)" = "timestamp.ago()"
