vim.opt.autoindent = true
vim.opt.background = 'dark'
vim.opt.backspace = {'indent', 'eol', 'start'}
vim.opt.backup = false
vim.opt.cmdheight = 2
vim.opt.colorcolumn = {81, 121}
vim.opt.compatible = false
vim.opt.cursorline = true
vim.opt.directory = vim.fn.stdpath('data') .. '/swap'
vim.opt.errorbells = false
vim.opt.expandtab = false 
vim.opt.foldenable = true
vim.opt.hidden = true
vim.opt.history = 100
vim.opt.hlsearch = true
vim.opt.ignorecase = true
vim.opt.incsearch = true
vim.opt.laststatus = 2
vim.opt.linebreak = true
vim.opt.linespace = 0
vim.opt.number = true
vim.opt.ruler = true
vim.opt.scrolljump = 1
vim.opt.scrolloff = 3
vim.opt.shiftwidth = 2
vim.opt.showcmd = true
vim.opt.showmatch = true
vim.opt.showmode = true
vim.opt.signcolumn = 'auto'
vim.opt.smartcase = true
vim.opt.smarttab = true
vim.opt.softtabstop = 2
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.swapfile = false
vim.opt.tabstop = 2
vim.opt.termguicolors = true
vim.opt.textwidth = 120
vim.opt.title = true
vim.opt.undodir = vim.fn.stdpath('data') .. '/undo'
vim.opt.undofile = true
vim.opt.updatetime = 300
vim.opt.virtualedit = ''
vim.opt.visualbell = true
vim.opt.wildmenu = true
vim.opt.wrap = true
vim.opt.writebackup = true
