vim.opt.autoindent = true
vim.opt.background = "dark"
vim.opt.backspace = {"indent", "eol", "start"}
vim.opt.backup = false
vim.opt.belloff = "all"
vim.opt.breakindent = true
vim.opt.cindent = true
vim.opt.clipboard = "unnamedplus"
vim.opt.cmdheight = 2
vim.opt.colorcolumn = {81, 121}
vim.opt.compatible = false
vim.opt.completeopt = {"menu", "menuone", "noselect"}
vim.opt.cursorline = true
vim.opt.diffopt = { "filler", "closeoff", "hiddenoff", "internal", "algorithm:minimal" }
vim.opt.directory = vim.fn.stdpath("data") .. "/swap"
vim.opt.equalalways = false
vim.opt.errorbells = false
vim.opt.expandtab = false
vim.opt.foldenable = true
vim.opt.foldlevel = 0
vim.opt.foldmethod = "marker"
vim.opt.formatoptions = vim.opt.formatoptions + "c"
vim.opt.formatoptions = vim.opt.formatoptions + "j"
vim.opt.formatoptions = vim.opt.formatoptions + "n"
vim.opt.formatoptions = vim.opt.formatoptions + "q"
vim.opt.formatoptions = vim.opt.formatoptions + "r"
vim.opt.formatoptions = vim.opt.formatoptions - "2"
vim.opt.formatoptions = vim.opt.formatoptions - "a"
vim.opt.formatoptions = vim.opt.formatoptions - "o"
vim.opt.formatoptions = vim.opt.formatoptions - "t"
vim.opt.hidden = true
vim.opt.history = 100
vim.opt.hlsearch = true
vim.opt.ignorecase = true
vim.opt.inccommand = "split"
vim.opt.incsearch = true
vim.opt.joinspaces = false
vim.opt.laststatus = 2
vim.opt.linebreak = true
vim.opt.linespace = 0
vim.opt.matchtime = 3
vim.opt.modelines = 1
vim.opt.mouse = "n"
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.ruler = true
vim.opt.scrolljump = 1
vim.opt.scrolloff = 10
vim.opt.shiftwidth = 4
vim.opt.showbreak = string.rep(" ", 3)
vim.opt.showcmd = true
vim.opt.showmode = true
vim.opt.signcolumn = "auto"
vim.opt.smartcase = true
vim.opt.smarttab = true
vim.opt.softtabstop = 4
vim.opt.splitbelow = true
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.splitright = true
vim.opt.swapfile = false
vim.opt.tabstop = 4
vim.opt.termguicolors = true
vim.opt.title = true
vim.opt.undodir = vim.fn.stdpath("data") .. "/undo"
vim.opt.undofile = true
vim.opt.updatetime = 300
vim.opt.virtualedit = ""
vim.opt.visualbell = true
vim.opt.wildmenu = true
vim.opt.wildmode = "longest:full"
vim.opt.wildoptions = "pum"
vim.opt.wrap = true
vim.opt.writebackup = true
